clean:
	rm -f OCODE junk core *~
	rm -f Xsquare anseq condcomp countdn junk monbfns monbfns1 monbfns6
	rm -f f3nplus1
	rm -f ack apfel bigprimes bprimes cavity coins coprimes
	rm -f crc crdemo d3nodes demo easter fact factors findperm
	rm -f fprimes fridays green
	rm -f ham23 hamming1 hamming2 hash2n hello huffman
	rm -f inpoly julian life nqueens objdemo pattern primefib primes
	rm -f prog queens queens1 queens2 queens3 queens4
	rm -f randtree ranexpr shtree splay
	rm -f squad squad1 squad2 squad3
	rm -f stvote tag triangle warshll milrabin genetic
