/*
This is a program that writes a file (INT.h) that
contains C #define statements that define BCPLINT32 and BCPLINT64
for the architecture that this program is running on. 
*/

#include <stdio.h>

int main() {
  printf("/* This file was generated by mkint-h */\n\n");

  // define BCPLINT32
  if (sizeof(int)==4) {
    printf("#define BCPLINT32 int\n");
    printf("#define BCPLUINT32 unsigned int\n");
    printf("#define FormD32 \"d\"\n");
    printf("#define FormX32 \"X\"\n");
    } else if (sizeof(long)==4) {
    printf("#define BCPLINT32 long\n");
    printf("#define BCPLUINT32 unsigned long\n");
    printf("#define FormD32 \"ld\"\n");
    printf("#define FormX32 \"lX\"\n");
  }

  // define BCPLINT64
  if (sizeof(int)==8){
    printf("#define BCPLINT64 int\n");
    printf("#define BCPLUINT64 unsigned int\n");
    printf("#define FormD64 \"d\"\n");
    printf("#define FormX64 \"X\"\n");
  } else if (sizeof(long)==8) {
    printf("#define BCPLINT64 long\n");
    printf("#define BCPLUINT64 unsigned long\n");
    printf("#define FormD64 \"ld\"\n");
    printf("#define FormX64 \"lX\"\n");
  } else if (sizeof(long long)==8) {
    printf("#define BCPLINT64 long long\n");
    printf("#define BCPLUINT64 unsigned long long\n");
    printf("#define FormD64 \"lld\"\n");
    printf("#define FormX64 \"llX\"\n");
  }
  return 0;
}
