/* This file was generated by mkint-h */

#define BCPLINT32 int
#define BCPLUINT32 unsigned int
#define FormD32 "d"
#define FormX32 "X"
#define BCPLINT64 long
#define BCPLUINT64 unsigned long
#define FormD64 "ld"
#define FormX64 "lX"
