# Code generated by sial-386

.text
.align 16
# MODSTART

# Entry to: start
# ENTRY   K5 C115 C116 C97 C114 C116
# LAB     L1

LA1:
 movl %ebp,0(%edx)
 movl %edx,%ebp
 popl %edx
 movl %edx,4(%ebp)
 movl %eax,8(%ebp)
 movl %ebx,12(%ebp)
# L       K1234
 movl $1234,%ebx
# SP      P3
 movl %ebx,12(%ebp)
# LW      M9001
 movl MA9001,%ebx
# SP      P4
 movl %ebx,16(%ebp)
# LW      M9002
 movl MA9002,%ebx
# SP      P5
 movl %ebx,20(%ebp)
# L       K0
 xorl %ebx,%ebx
# SP      P6
 movl %ebx,24(%ebp)
# FNEG
# unimplemented
# SP      P7
 movl %ebx,28(%ebp)
# LP      P4
 movl 16(%ebp),%ebx
# FIX
# unimplemented
# SP      P8
 movl %ebx,32(%ebp)
# LP      P5
 movl 20(%ebp),%ebx
# FIX
# unimplemented
# SP      P9
 movl %ebx,36(%ebp)
# LP      P4
 movl 16(%ebp),%ebx
# FABS
# unimplemented
# SP      P11
 movl %ebx,44(%ebp)
# LP      P5
 movl 20(%ebp),%ebx
# FABS
# unimplemented
# SP      P12
 movl %ebx,48(%ebp)
# LW      M9003
 movl MA9003,%ebx
# SP      P10
 movl %ebx,40(%ebp)
# LP      P5
 movl 20(%ebp),%ebx
# ATBLP   P4
 movl %ebx,%ecx
 movl 16(%ebp),%ebx
# FMUL
# unimplemented
# ATBLP   P10
 movl %ebx,%ecx
 movl 40(%ebp),%ebx
# FDIV
# unimplemented
# SP      P13
 movl %ebx,52(%ebp)
# LP      P5
 movl 20(%ebp),%ebx
# ATBLP   P4
 movl %ebx,%ecx
 movl 16(%ebp),%ebx
# FADD
# unimplemented
# ATBLP   P10
 movl %ebx,%ecx
 movl 40(%ebp),%ebx
# FSUB
# unimplemented
# SP      P14
 movl %ebx,56(%ebp)
# LP      P5
 movl 20(%ebp),%ebx
# SP      P15
 movl %ebx,60(%ebp)
# LLL     L6
 leal LA6,%ebx
 shrl $2,%ebx
# SP      P16
 movl %ebx,64(%ebp)
# LSTR    M9004
 leal MA9004,%ebx
 shrl $2,%ebx
# KPG     P17 G94
 movl 376(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LKP     K0 P16
 movl 64(%ebp),%eax
 movl 0(,%eax,4),%ebx
# ATB
 movl %ebx,%ecx
# LF      L4
 leal LA4,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# KPG     P17 G84
 movl 336(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LSTR    M9005
 leal MA9005,%ebx
 shrl $2,%ebx
# KPG     P17 G94
 movl 376(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LKP     K1 P16
 movl 64(%ebp),%eax
 movl 4(,%eax,4),%ebx
# ATB
 movl %ebx,%ecx
# LF      L4
 leal LA4,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# KPG     P17 G84
 movl 336(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LSTR    M9006
 leal MA9006,%ebx
 shrl $2,%ebx
# KPG     P17 G94
 movl 376(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LKP     K2 P16
 movl 64(%ebp),%eax
 movl 8(,%eax,4),%ebx
# ATB
 movl %ebx,%ecx
# LF      L4
 leal LA4,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# KPG     P17 G84
 movl 336(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LSTR    M9007
 leal MA9007,%ebx
 shrl $2,%ebx
# KPG     P17 G94
 movl 376(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LKP     K3 P16
 movl 64(%ebp),%eax
 movl 12(,%eax,4),%ebx
# ATB
 movl %ebx,%ecx
# LF      L4
 leal LA4,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# KPG     P17 G84
 movl 336(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LSTR    M9008
 leal MA9008,%ebx
 shrl $2,%ebx
# KPG     P17 G94
 movl 376(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LKP     K4 P16
 movl 64(%ebp),%eax
 movl 16(,%eax,4),%ebx
# ATB
 movl %ebx,%ecx
# LF      L4
 leal LA4,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# KPG     P17 G84
 movl 336(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LSTR    M9009
 leal MA9009,%ebx
 shrl $2,%ebx
# KPG     P17 G94
 movl 376(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LKP     K5 P16
 movl 64(%ebp),%eax
 movl 20(,%eax,4),%ebx
# ATB
 movl %ebx,%ecx
# LF      L4
 leal LA4,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# KPG     P17 G84
 movl 336(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LSTR    M9010
 leal MA9010,%ebx
 shrl $2,%ebx
# KPG     P17 G94
 movl 376(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LKP     K6 P16
 movl 64(%ebp),%eax
 movl 24(,%eax,4),%ebx
# ATB
 movl %ebx,%ecx
# LF      L4
 leal LA4,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# KPG     P17 G84
 movl 336(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LSTR    M9011
 leal MA9011,%ebx
 shrl $2,%ebx
# KPG     P17 G94
 movl 376(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LKP     K7 P16
 movl 64(%ebp),%eax
 movl 28(,%eax,4),%ebx
# ATB
 movl %ebx,%ecx
# LF      L4
 leal LA4,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# KPG     P17 G84
 movl 336(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LSTR    M9012
 leal MA9012,%ebx
 shrl $2,%ebx
# KPG     P17 G94
 movl 376(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LKP     K8 P16
 movl 64(%ebp),%eax
 movl 32(,%eax,4),%ebx
# ATB
 movl %ebx,%ecx
# LF      L4
 leal LA4,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# KPG     P17 G84
 movl 336(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LSTR    M9013
 leal MA9013,%ebx
 shrl $2,%ebx
# KPG     P17 G94
 movl 376(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LKP     K9 P16
 movl 64(%ebp),%eax
 movl 36(,%eax,4),%ebx
# ATB
 movl %ebx,%ecx
# LF      L4
 leal LA4,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# KPG     P17 G84
 movl 336(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# L       K0
 xorl %ebx,%ebx
# SG      G200
 movl %ebx,800(%esi)
# SG      G201
 movl %ebx,804(%esi)
# LP      P4
 movl 16(%ebp),%ebx
# ATBLP   P4
 movl %ebx,%ecx
 movl 16(%ebp),%ebx
# FLE
# unimplemented
# JEQ0    L7
 orl %ebx,%ebx
 je LA7
# LSTR    M9014
 leal MA9014,%ebx
 shrl $2,%ebx
# KPG     P17 G94
 movl 376(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LAB     L7
LA7:
# LP      P4
 movl 16(%ebp),%ebx
# ATBLP   P4
 movl %ebx,%ecx
 movl 16(%ebp),%ebx
# FGE
# unimplemented
# JEQ0    L8
 orl %ebx,%ebx
 je LA8
# LSTR    M9015
 leal MA9015,%ebx
 shrl $2,%ebx
# KPG     P17 G94
 movl 376(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LAB     L8
LA8:
# LP      P4
 movl 16(%ebp),%ebx
# ATBLP   P4
 movl %ebx,%ecx
 movl 16(%ebp),%ebx
# FGE
# unimplemented
# JEQ0    L9
 orl %ebx,%ebx
 je LA9
# LSTR    M9016
 leal MA9016,%ebx
 shrl $2,%ebx
# KPG     P17 G94
 movl 376(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LAB     L9
LA9:
# LP      P4
 movl 16(%ebp),%ebx
# ATBLP   P5
 movl %ebx,%ecx
 movl 20(%ebp),%ebx
# FGE
# unimplemented
# JEQ0    L10
 orl %ebx,%ebx
 je LA10
# LSTR    M9017
 leal MA9017,%ebx
 shrl $2,%ebx
# KPG     P17 G94
 movl 376(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LAB     L10
LA10:
# LP      P7
 movl 28(%ebp),%ebx
# ATBLP   P6
 movl %ebx,%ecx
 movl 24(%ebp),%ebx
# FEQ
# unimplemented
# JEQ0    L11
 orl %ebx,%ebx
 je LA11
# LSTR    M9018
 leal MA9018,%ebx
 shrl $2,%ebx
# KPG     P17 G94
 movl 376(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LAB     L11
LA11:
# LP      P8
 movl 32(%ebp),%ebx
# SP      P21
 movl %ebx,84(%ebp)
# LP      P9
 movl 36(%ebp),%ebx
# SP      P22
 movl %ebx,88(%ebp)
# LSTR    M9019
 leal MA9019,%ebx
 shrl $2,%ebx
# KPG     P17 G94
 movl 376(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LW      M9020
 movl MA9020,%ebx
# ATBLP   P10
 movl %ebx,%ecx
 movl 40(%ebp),%ebx
# FNE
# unimplemented
# JEQ0    L12
 orl %ebx,%ebx
 je LA12
# LSTR    M9021
 leal MA9021,%ebx
 shrl $2,%ebx
# KPG     P17 G94
 movl 376(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LAB     L12
LA12:
# LP      P10
 movl 40(%ebp),%ebx
# ATB
 movl %ebx,%ecx
# LW      M9022
 movl MA9022,%ebx
# FLS
# unimplemented
# JEQ0    L13
 orl %ebx,%ebx
 je LA13
# LSTR    M9023
 leal MA9023,%ebx
 shrl $2,%ebx
# KPG     P17 G94
 movl 376(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LAB     L13
LA13:
# LP      P10
 movl 40(%ebp),%ebx
# ATB
 movl %ebx,%ecx
# LW      M9024
 movl MA9024,%ebx
# FGR
# unimplemented
# JEQ0    L14
 orl %ebx,%ebx
 je LA14
# LSTR    M9025
 leal MA9025,%ebx
 shrl $2,%ebx
# KPG     P17 G94
 movl 376(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# LAB     L14
LA14:
# LP      P5
 movl 20(%ebp),%ebx
# FNEG
# unimplemented
# SP      P21
 movl %ebx,84(%ebp)
# LW      M9026
 movl MA9026,%ebx
# ATB
 movl %ebx,%ecx
# LF      L2
 leal LA2,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# L       K0
 xorl %ebx,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# LW      M9027
 movl MA9027,%ebx
# ATB
 movl %ebx,%ecx
# LF      L2
 leal LA2,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LW      M9029
 movl MA9029,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# LW      M9028
 movl MA9028,%ebx
# ATB
 movl %ebx,%ecx
# LF      L2
 leal LA2,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# L       K12
 movl $12,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LM      K12
 movl $-12,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LW      M9031
 movl MA9031,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# LW      M9030
 movl MA9030,%ebx
# ATB
 movl %ebx,%ecx
# LF      L2
 leal LA2,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LW      M9033
 movl MA9033,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# LW      M9032
 movl MA9032,%ebx
# ATB
 movl %ebx,%ecx
# LF      L2
 leal LA2,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LW      M9035
 movl MA9035,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# LW      M9034
 movl MA9034,%ebx
# ATB
 movl %ebx,%ecx
# LF      L2
 leal LA2,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LW      M9037
 movl MA9037,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# LW      M9036
 movl MA9036,%ebx
# ATB
 movl %ebx,%ecx
# LF      L2
 leal LA2,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LW      M9039
 movl MA9039,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# LW      M9038
 movl MA9038,%ebx
# ATB
 movl %ebx,%ecx
# LF      L2
 leal LA2,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LM      K1
 movl $-1,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# L       K0
 xorl %ebx,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# L       K0
 xorl %ebx,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LM      K1
 movl $-1,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# L       K0
 xorl %ebx,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LM      K1
 movl $-1,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LM      K1
 movl $-1,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LM      K1
 movl $-1,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LM      K1
 movl $-1,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# L       K0
 xorl %ebx,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# L       K0
 xorl %ebx,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# L       K0
 xorl %ebx,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LM      K1
 movl $-1,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LM      K1
 movl $-1,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# L       K0
 xorl %ebx,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# L       K0
 xorl %ebx,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# L       K30
 movl $30,%ebx
# SG      G200
 movl %ebx,800(%esi)
# LW      M9040
 movl MA9040,%ebx
# ATBLP   P4
 movl %ebx,%ecx
 movl 16(%ebp),%ebx
# FEQ
# unimplemented
# ATB
 movl %ebx,%ecx
# LM      K1
 movl $-1,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# XCH
 xchgl %ebx,%ecx
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LW      M9041
 movl MA9041,%ebx
# ATBLP   P4
 movl %ebx,%ecx
 movl 16(%ebp),%ebx
# FEQ
# unimplemented
# ATB
 movl %ebx,%ecx
# L       K0
 xorl %ebx,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# XCH
 xchgl %ebx,%ecx
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LW      M9042
 movl MA9042,%ebx
# ATBLP   P4
 movl %ebx,%ecx
 movl 16(%ebp),%ebx
# FNE
# unimplemented
# ATB
 movl %ebx,%ecx
# L       K0
 xorl %ebx,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# XCH
 xchgl %ebx,%ecx
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LW      M9043
 movl MA9043,%ebx
# ATBLP   P4
 movl %ebx,%ecx
 movl 16(%ebp),%ebx
# FNE
# unimplemented
# ATB
 movl %ebx,%ecx
# LM      K1
 movl $-1,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# XCH
 xchgl %ebx,%ecx
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LP      P4
 movl 16(%ebp),%ebx
# ATB
 movl %ebx,%ecx
# LW      M9044
 movl MA9044,%ebx
# FLE
# unimplemented
# ATB
 movl %ebx,%ecx
# L       K0
 xorl %ebx,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# XCH
 xchgl %ebx,%ecx
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LP      P4
 movl 16(%ebp),%ebx
# ATB
 movl %ebx,%ecx
# LW      M9045
 movl MA9045,%ebx
# FLE
# unimplemented
# ATB
 movl %ebx,%ecx
# LM      K1
 movl $-1,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# XCH
 xchgl %ebx,%ecx
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LP      P4
 movl 16(%ebp),%ebx
# ATB
 movl %ebx,%ecx
# LW      M9046
 movl MA9046,%ebx
# FLE
# unimplemented
# ATB
 movl %ebx,%ecx
# LM      K1
 movl $-1,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# XCH
 xchgl %ebx,%ecx
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LP      P4
 movl 16(%ebp),%ebx
# ATB
 movl %ebx,%ecx
# LW      M9047
 movl MA9047,%ebx
# FGE
# unimplemented
# ATB
 movl %ebx,%ecx
# LM      K1
 movl $-1,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# XCH
 xchgl %ebx,%ecx
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LP      P4
 movl 16(%ebp),%ebx
# ATB
 movl %ebx,%ecx
# LW      M9048
 movl MA9048,%ebx
# FGE
# unimplemented
# ATB
 movl %ebx,%ecx
# LM      K1
 movl $-1,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# XCH
 xchgl %ebx,%ecx
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LP      P4
 movl 16(%ebp),%ebx
# ATB
 movl %ebx,%ecx
# LW      M9049
 movl MA9049,%ebx
# FGE
# unimplemented
# ATB
 movl %ebx,%ecx
# L       K0
 xorl %ebx,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# XCH
 xchgl %ebx,%ecx
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LP      P4
 movl 16(%ebp),%ebx
# ATB
 movl %ebx,%ecx
# LW      M9050
 movl MA9050,%ebx
# FLS
# unimplemented
# ATB
 movl %ebx,%ecx
# L       K0
 xorl %ebx,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# XCH
 xchgl %ebx,%ecx
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LP      P4
 movl 16(%ebp),%ebx
# ATB
 movl %ebx,%ecx
# LW      M9051
 movl MA9051,%ebx
# FLS
# unimplemented
# ATB
 movl %ebx,%ecx
# L       K0
 xorl %ebx,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# XCH
 xchgl %ebx,%ecx
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LP      P4
 movl 16(%ebp),%ebx
# ATB
 movl %ebx,%ecx
# LW      M9052
 movl MA9052,%ebx
# FLS
# unimplemented
# ATB
 movl %ebx,%ecx
# LM      K1
 movl $-1,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# XCH
 xchgl %ebx,%ecx
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LP      P4
 movl 16(%ebp),%ebx
# ATB
 movl %ebx,%ecx
# LW      M9053
 movl MA9053,%ebx
# FGR
# unimplemented
# ATB
 movl %ebx,%ecx
# LM      K1
 movl $-1,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# XCH
 xchgl %ebx,%ecx
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LP      P4
 movl 16(%ebp),%ebx
# ATB
 movl %ebx,%ecx
# LW      M9054
 movl MA9054,%ebx
# FGR
# unimplemented
# ATB
 movl %ebx,%ecx
# L       K0
 xorl %ebx,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# XCH
 xchgl %ebx,%ecx
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LP      P4
 movl 16(%ebp),%ebx
# ATB
 movl %ebx,%ecx
# LW      M9055
 movl MA9055,%ebx
# FGR
# unimplemented
# ATB
 movl %ebx,%ecx
# L       K0
 xorl %ebx,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# XCH
 xchgl %ebx,%ecx
# ATB
 movl %ebx,%ecx
# LF      L3
 leal LA3,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# L       K100
 movl $100,%ebx
# SG      G200
 movl %ebx,800(%esi)
# LW      M9057
 movl MA9057,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# LW      M9056
 movl MA9056,%ebx
# ATB
 movl %ebx,%ecx
# LF      L2
 leal LA2,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LW      M9059
 movl MA9059,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# LW      M9058
 movl MA9058,%ebx
# ATB
 movl %ebx,%ecx
# LF      L2
 leal LA2,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LW      M9061
 movl MA9061,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# LW      M9060
 movl MA9060,%ebx
# ATB
 movl %ebx,%ecx
# LF      L2
 leal LA2,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LW      M9063
 movl MA9063,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# LW      M9062
 movl MA9062,%ebx
# ATB
 movl %ebx,%ecx
# LF      L2
 leal LA2,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LW      M9065
 movl MA9065,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# LW      M9064
 movl MA9064,%ebx
# ATB
 movl %ebx,%ecx
# LF      L2
 leal LA2,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LW      M9067
 movl MA9067,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# LW      M9066
 movl MA9066,%ebx
# ATB
 movl %ebx,%ecx
# LF      L2
 leal LA2,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LW      M9069
 movl MA9069,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# LW      M9068
 movl MA9068,%ebx
# ATB
 movl %ebx,%ecx
# LF      L2
 leal LA2,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LP      P3
 movl 12(%ebp),%ebx
# FLOAT
# unimplemented
# ATB
 movl %ebx,%ecx
# LW      M9070
 movl MA9070,%ebx
# SP      P21
 movl %ebx,84(%ebp)
# XCH
 xchgl %ebx,%ecx
# ATB
 movl %ebx,%ecx
# LF      L2
 leal LA2,%ebx
# K       P17
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 68(%ebp),%edx
 call *%eax
# LG      G201
 movl 804(%esi),%ebx
# SP      P21
 movl %ebx,84(%ebp)
# LSTR    M9071
 leal MA9071,%ebx
 shrl $2,%ebx
# KPG     P17 G94
 movl 376(%esi),%eax
 leal 68(%ebp),%edx
 call *%eax
# L       K0
 xorl %ebx,%ebx
# RTN
 movl 4(%ebp),%eax
 movl 0(%ebp),%ebp
 jmp *%eax
# CONST   M9001 W1067316150
.data
 .align 4
MA9001:
 .long 1067316150
 .text
# CONST   M9002 W-1080167498
.data
 .align 4
MA9002:
 .long -1080167498
 .text
# CONST   M9003 W1150959616
.data
 .align 4
MA9003:
 .long 1150959616
 .text
# CONST   M9020 W1150960435
.data
 .align 4
MA9020:
 .long 1150960435
 .text
# CONST   M9022 W1150960435
.data
 .align 4
MA9022:
 .long 1150960435
 .text
# CONST   M9024 W1150958797
.data
 .align 4
MA9024:
 .long 1150958797
 .text
# CONST   M9026 W1067316150
.data
 .align 4
MA9026:
 .long 1067316150
 .text
# CONST   M9027 W-2147483648
.data
 .align 4
MA9027:
 .long -2147483648
 .text
# CONST   M9028 W1067316150
.data
 .align 4
MA9028:
 .long 1067316150
 .text
# CONST   M9029 W1067316150
.data
 .align 4
MA9029:
 .long 1067316150
 .text
# CONST   M9030 W1141948416
.data
 .align 4
MA9030:
 .long 1141948416
 .text
# CONST   M9031 W1141948416
.data
 .align 4
MA9031:
 .long 1141948416
 .text
# CONST   M9032 W1075704758
.data
 .align 4
MA9032:
 .long 1075704758
 .text
# CONST   M9033 W1075704758
.data
 .align 4
MA9033:
 .long 1075704758
 .text
# CONST   M9034 W1061158912
.data
 .align 4
MA9034:
 .long 1061158912
 .text
# CONST   M9035 W1061158912
.data
 .align 4
MA9035:
 .long 1061158912
 .text
# CONST   M9036 W1078917595
.data
 .align 4
MA9036:
 .long 1078917595
 .text
# CONST   M9037 W1078917595
.data
 .align 4
MA9037:
 .long 1078917595
 .text
# CONST   M9038 W-1090519040
.data
 .align 4
MA9038:
 .long -1090519040
 .text
# CONST   M9039 W-1090519040
.data
 .align 4
MA9039:
 .long -1090519040
 .text
# CONST   M9040 W1067316150
.data
 .align 4
MA9040:
 .long 1067316150
 .text
# CONST   M9041 W1067324539
.data
 .align 4
MA9041:
 .long 1067324539
 .text
# CONST   M9042 W1067316150
.data
 .align 4
MA9042:
 .long 1067316150
 .text
# CONST   M9043 W1067324539
.data
 .align 4
MA9043:
 .long 1067324539
 .text
# CONST   M9044 W1067307762
.data
 .align 4
MA9044:
 .long 1067307762
 .text
# CONST   M9045 W1067316150
.data
 .align 4
MA9045:
 .long 1067316150
 .text
# CONST   M9046 W1067324539
.data
 .align 4
MA9046:
 .long 1067324539
 .text
# CONST   M9047 W1067307762
.data
 .align 4
MA9047:
 .long 1067307762
 .text
# CONST   M9048 W1067316150
.data
 .align 4
MA9048:
 .long 1067316150
 .text
# CONST   M9049 W1067324539
.data
 .align 4
MA9049:
 .long 1067324539
 .text
# CONST   M9050 W1067307762
.data
 .align 4
MA9050:
 .long 1067307762
 .text
# CONST   M9051 W1067316150
.data
 .align 4
MA9051:
 .long 1067316150
 .text
# CONST   M9052 W1067324539
.data
 .align 4
MA9052:
 .long 1067324539
 .text
# CONST   M9053 W1067307762
.data
 .align 4
MA9053:
 .long 1067307762
 .text
# CONST   M9054 W1067316150
.data
 .align 4
MA9054:
 .long 1067316150
 .text
# CONST   M9055 W1067316150
.data
 .align 4
MA9055:
 .long 1067316150
 .text
# CONST   M9056 W1065353216
.data
 .align 4
MA9056:
 .long 1065353216
 .text
# CONST   M9057 W1065353216
.data
 .align 4
MA9057:
 .long 1065353216
 .text
# CONST   M9058 W1073741824
.data
 .align 4
MA9058:
 .long 1073741824
 .text
# CONST   M9059 W1073741824
.data
 .align 4
MA9059:
 .long 1073741824
 .text
# CONST   M9060 W1077936128
.data
 .align 4
MA9060:
 .long 1077936128
 .text
# CONST   M9061 W1077936128
.data
 .align 4
MA9061:
 .long 1077936128
 .text
# CONST   M9062 W-1082130432
.data
 .align 4
MA9062:
 .long -1082130432
 .text
# CONST   M9063 W-1082130432
.data
 .align 4
MA9063:
 .long -1082130432
 .text
# CONST   M9064 W-1073741824
.data
 .align 4
MA9064:
 .long -1073741824
 .text
# CONST   M9065 W-1073741824
.data
 .align 4
MA9065:
 .long -1073741824
 .text
# CONST   M9066 W-1069547520
.data
 .align 4
MA9066:
 .long -1069547520
 .text
# CONST   M9067 W-1069547520
.data
 .align 4
MA9067:
 .long -1069547520
 .text
# CONST   M9068 W1150959616
.data
 .align 4
MA9068:
 .long 1150959616
 .text
# CONST   M9069 W1150959616
.data
 .align 4
MA9069:
 .long 1150959616
 .text
# CONST   M9070 W1150959616
.data
 .align 4
MA9070:
 .long 1150959616
 .text
# STATIC  L6 K10
.data
 .align 4
LA6:
# W1065353216
 .long 1065353216
# W1073741824
 .long 1073741824
# W1077936128
 .long 1077936128
# W-1082130432
 .long -1082130432
# W-1082130432
 .long -1082130432
# W1086324736
 .long 1086324736
# W1059760811
 .long 1059760811
# W1069547520
 .long 1069547520
# W1069547520
 .long 1069547520
# W1084227584
 .long 1084227584
 .text
# STRING  M9004 K14 C49 C46 C48 C58 C32 C32 C32 C32 C32 C32 C32 C32 C32 C32
.data
 .align 4
MA9004:
 .byte 14
 .byte 49
 .byte 46
 .byte 48
 .byte 58
 .byte 32
 .byte 32
 .byte 32
 .byte 32
 .byte 32
 .byte 32
 .byte 32
 .byte 32
 .byte 32
 .byte 32
 .text
# STRING  M9005 K14 C50 C46 C48 C58 C32 C32 C32 C32 C32 C32 C32 C32 C32 C32
.data
 .align 4
MA9005:
 .byte 14
 .byte 50
 .byte 46
 .byte 48
 .byte 58
 .byte 32
 .byte 32
 .byte 32
 .byte 32
 .byte 32
 .byte 32
 .byte 32
 .byte 32
 .byte 32
 .byte 32
 .text
# STRING  M9006 K14 C49 C46 C48 C32 C35 C43 C32 C50 C46 C48 C58 C32 C32 C32
.data
 .align 4
MA9006:
 .byte 14
 .byte 49
 .byte 46
 .byte 48
 .byte 32
 .byte 35
 .byte 43
 .byte 32
 .byte 50
 .byte 46
 .byte 48
 .byte 58
 .byte 32
 .byte 32
 .byte 32
 .text
# STRING  M9007 K14 C49 C46 C48 C32 C35 C45 C32 C50 C46 C48 C58 C32 C32 C32
.data
 .align 4
MA9007:
 .byte 14
 .byte 49
 .byte 46
 .byte 48
 .byte 32
 .byte 35
 .byte 45
 .byte 32
 .byte 50
 .byte 46
 .byte 48
 .byte 58
 .byte 32
 .byte 32
 .byte 32
 .text
# STRING  M9008 K14 C35 C45 C32 C49 C46 C48 C58 C32 C32 C32 C32 C32 C32 C32
.data
 .align 4
MA9008:
 .byte 14
 .byte 35
 .byte 45
 .byte 32
 .byte 49
 .byte 46
 .byte 48
 .byte 58
 .byte 32
 .byte 32
 .byte 32
 .byte 32
 .byte 32
 .byte 32
 .byte 32
 .text
# STRING  M9009 K14 C50 C46 C48 C32 C35 C42 C32 C51 C46 C48 C58 C32 C32 C32
.data
 .align 4
MA9009:
 .byte 14
 .byte 50
 .byte 46
 .byte 48
 .byte 32
 .byte 35
 .byte 42
 .byte 32
 .byte 51
 .byte 46
 .byte 48
 .byte 58
 .byte 32
 .byte 32
 .byte 32
 .text
# STRING  M9010 K14 C50 C46 C48 C32 C35 C47 C32 C51 C46 C48 C58 C32 C32 C32
.data
 .align 4
MA9010:
 .byte 14
 .byte 50
 .byte 46
 .byte 48
 .byte 32
 .byte 35
 .byte 47
 .byte 32
 .byte 51
 .byte 46
 .byte 48
 .byte 58
 .byte 32
 .byte 32
 .byte 32
 .text
# STRING  M9011 K14 C35 C65 C66 C83 C32 C40 C35 C45 C32 C49 C46 C53 C41 C32
.data
 .align 4
MA9011:
 .byte 14
 .byte 35
 .byte 65
 .byte 66
 .byte 83
 .byte 32
 .byte 40
 .byte 35
 .byte 45
 .byte 32
 .byte 49
 .byte 46
 .byte 53
 .byte 41
 .byte 32
 .text
# STRING  M9012 K14 C35 C65 C66 C83 C32 C40 C35 C43 C32 C49 C46 C53 C41 C32
.data
 .align 4
MA9012:
 .byte 14
 .byte 35
 .byte 65
 .byte 66
 .byte 83
 .byte 32
 .byte 40
 .byte 35
 .byte 43
 .byte 32
 .byte 49
 .byte 46
 .byte 53
 .byte 41
 .byte 32
 .text
# STRING  M9013 K14 C70 C76 C79 C65 C84 C32 C53 C58 C32 C32 C32 C32 C32 C32
.data
 .align 4
MA9013:
 .byte 14
 .byte 70
 .byte 76
 .byte 79
 .byte 65
 .byte 84
 .byte 32
 .byte 53
 .byte 58
 .byte 32
 .byte 32
 .byte 32
 .byte 32
 .byte 32
 .byte 32
 .text
# STRING  M9014 K5 C97 C60 C61 C97 C10
.data
 .align 4
MA9014:
 .byte 5
 .byte 97
 .byte 60
 .byte 61
 .byte 97
 .byte 10
 .text
# STRING  M9015 K5 C97 C62 C61 C97 C10
.data
 .align 4
MA9015:
 .byte 5
 .byte 97
 .byte 62
 .byte 61
 .byte 97
 .byte 10
 .text
# STRING  M9016 K5 C97 C62 C61 C97 C10
.data
 .align 4
MA9016:
 .byte 5
 .byte 97
 .byte 62
 .byte 61
 .byte 97
 .byte 10
 .text
# STRING  M9017 K5 C97 C62 C61 C98 C10
.data
 .align 4
MA9017:
 .byte 5
 .byte 97
 .byte 62
 .byte 61
 .byte 98
 .byte 10
 .text
# STRING  M9018 K5 C99 C62 C61 C100 C10
.data
 .align 4
MA9018:
 .byte 5
 .byte 99
 .byte 62
 .byte 61
 .byte 100
 .byte 10
 .text
# STRING  M9019 K10 C101 C61 C37 C110 C32 C102 C61 C37 C110 C10
.data
 .align 4
MA9019:
 .byte 10
 .byte 101
 .byte 61
 .byte 37
 .byte 110
 .byte 32
 .byte 102
 .byte 61
 .byte 37
 .byte 110
 .byte 10
 .text
# STRING  M9021 K13 C103 C32 C35 C126 C61 C32 C49 C50 C51 C52 C46 C49 C10
.data
 .align 4
MA9021:
 .byte 13
 .byte 103
 .byte 32
 .byte 35
 .byte 126
 .byte 61
 .byte 32
 .byte 49
 .byte 50
 .byte 51
 .byte 52
 .byte 46
 .byte 49
 .byte 10
 .text
# STRING  M9023 K12 C103 C32 C35 C60 C32 C49 C50 C51 C52 C46 C49 C10
.data
 .align 4
MA9023:
 .byte 12
 .byte 103
 .byte 32
 .byte 35
 .byte 60
 .byte 32
 .byte 49
 .byte 50
 .byte 51
 .byte 52
 .byte 46
 .byte 49
 .byte 10
 .text
# STRING  M9025 K12 C103 C32 C35 C62 C32 C49 C50 C51 C51 C46 C57 C10
.data
 .align 4
MA9025:
 .byte 12
 .byte 103
 .byte 32
 .byte 35
 .byte 62
 .byte 32
 .byte 49
 .byte 50
 .byte 51
 .byte 51
 .byte 46
 .byte 57
 .byte 10
 .text
# STRING  M9071 K43 C10 C69 C110 C100 C32 C111 C102 C32 C102 C108 C111 C97 C116 C105 C110 C103 C32 C112 C111 C105 C110 C116 C32 C116 C101 C115 C116 C44 C32 C37 C110 C32 C101 C114 C114 C111 C114 C37 C45 C37 C112 C115 C10
.data
 .align 4
MA9071:
 .byte 43
 .byte 10
 .byte 69
 .byte 110
 .byte 100
 .byte 32
 .byte 111
 .byte 102
 .byte 32
 .byte 102
 .byte 108
 .byte 111
 .byte 97
 .byte 116
 .byte 105
 .byte 110
 .byte 103
 .byte 32
 .byte 112
 .byte 111
 .byte 105
 .byte 110
 .byte 116
 .byte 32
 .byte 116
 .byte 101
 .byte 115
 .byte 116
 .byte 44
 .byte 32
 .byte 37
 .byte 110
 .byte 32
 .byte 101
 .byte 114
 .byte 114
 .byte 111
 .byte 114
 .byte 37
 .byte 45
 .byte 37
 .byte 112
 .byte 115
 .byte 10
 .text

# Entry to: t
# ENTRY   K1 C116
# LAB     L2

LA2:
 movl %ebp,0(%edx)
 movl %edx,%ebp
 popl %edx
 movl %edx,4(%ebp)
 movl %eax,8(%ebp)
 movl %ebx,12(%ebp)
# IKG     K1 G200
 movl 800(%esi),%ebx
 incl %ebx
 movl %ebx,800(%esi)
# SP      P9
 movl %ebx,36(%ebp)
# LSTR    M9072
 leal MA9072,%ebx
 shrl $2,%ebx
# KPG     P5 G94
 movl 376(%esi),%eax
 leal 20(%ebp),%edx
 call *%eax
# LP      P3
 movl 12(%ebp),%ebx
# ATB
 movl %ebx,%ecx
# LF      L4
 leal LA4,%ebx
# K       P5
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 20(%ebp),%edx
 call *%eax
# LP      P4
 movl 16(%ebp),%ebx
# ATB
 movl %ebx,%ecx
# LF      L4
 leal LA4,%ebx
# K       P5
 movl %ebx,%eax
 movl %ecx,%ebx
 leal 20(%ebp),%edx
 call *%eax
# LP      P4
 movl 16(%ebp),%ebx
# ATBLP   P3
 movl %ebx,%ecx
 movl 12(%ebp),%ebx
# FEQ
# unimplemented
# JEQ0    L15
 orl %ebx,%ebx
 je LA15
# LSTR    M9073
 leal MA9073,%ebx
 shrl $2,%ebx
# KPG     P5 G94
 movl 376(%esi),%eax
 leal 20(%ebp),%edx
 call *%eax
# RTN
 movl 4(%ebp),%eax
 movl 0(%ebp),%ebp
 jmp *%eax
# LAB     L15
LA15:
# LSTR    M9074
 leal MA9074,%ebx
 shrl $2,%ebx
# KPG     P5 G94
 movl 376(%esi),%eax
 leal 20(%ebp),%edx
 call *%eax
# IKG     K1 G201
 movl 804(%esi),%ebx
 incl %ebx
 movl %ebx,804(%esi)
# RTN
 movl 4(%ebp),%eax
 movl 0(%ebp),%ebp
 jmp *%eax
# STRING  M9072 K5 C37 C105 C51 C58 C32
.data
 .align 4
MA9072:
 .byte 5
 .byte 37
 .byte 105
 .byte 51
 .byte 58
 .byte 32
 .text
# STRING  M9073 K4 C32 C79 C75 C10
.data
 .align 4
MA9073:
 .byte 4
 .byte 32
 .byte 79
 .byte 75
 .byte 10
 .text
# STRING  M9074 K5 C32 C66 C65 C68 C10
.data
 .align 4
MA9074:
 .byte 5
 .byte 32
 .byte 66
 .byte 65
 .byte 68
 .byte 10
 .text

# Entry to: tb
# ENTRY   K2 C116 C98
# LAB     L3

LA3:
 movl %ebp,0(%edx)
 movl %edx,%ebp
 popl %edx
 movl %edx,4(%ebp)
 movl %eax,8(%ebp)
 movl %ebx,12(%ebp)
# IKG     K1 G200
 movl 800(%esi),%ebx
 incl %ebx
 movl %ebx,800(%esi)
# SP      P9
 movl %ebx,36(%ebp)
# LP      P3
 movl 12(%ebp),%ebx
# SP      P10
 movl %ebx,40(%ebp)
# LP      P4
 movl 16(%ebp),%ebx
# SP      P11
 movl %ebx,44(%ebp)
# LSTR    M9075
 leal MA9075,%ebx
 shrl $2,%ebx
# KPG     P5 G94
 movl 376(%esi),%eax
 leal 20(%ebp),%edx
 call *%eax
# LP      P4
 movl 16(%ebp),%ebx
# ATBLP   P3
 movl %ebx,%ecx
 movl 12(%ebp),%ebx
# JNE     L16
 cmpl %ebx,%ecx
 jne LA16
# LSTR    M9076
 leal MA9076,%ebx
 shrl $2,%ebx
# KPG     P5 G94
 movl 376(%esi),%eax
 leal 20(%ebp),%edx
 call *%eax
# RTN
 movl 4(%ebp),%eax
 movl 0(%ebp),%ebp
 jmp *%eax
# LAB     L16
LA16:
# LSTR    M9077
 leal MA9077,%ebx
 shrl $2,%ebx
# KPG     P5 G94
 movl 376(%esi),%eax
 leal 20(%ebp),%edx
 call *%eax
# IKG     K1 G201
 movl 804(%esi),%ebx
 incl %ebx
 movl %ebx,804(%esi)
# RTN
 movl 4(%ebp),%eax
 movl 0(%ebp),%ebp
 jmp *%eax
# STRING  M9075 K16 C37 C105 C51 C58 C32 C120 C61 C37 C105 C50 C32 C121 C61 C37 C105 C50
.data
 .align 4
MA9075:
 .byte 16
 .byte 37
 .byte 105
 .byte 51
 .byte 58
 .byte 32
 .byte 120
 .byte 61
 .byte 37
 .byte 105
 .byte 50
 .byte 32
 .byte 121
 .byte 61
 .byte 37
 .byte 105
 .byte 50
 .text
# STRING  M9076 K4 C32 C79 C75 C10
.data
 .align 4
MA9076:
 .byte 4
 .byte 32
 .byte 79
 .byte 75
 .byte 10
 .text
# STRING  M9077 K5 C32 C66 C65 C68 C10
.data
 .align 4
MA9077:
 .byte 5
 .byte 32
 .byte 66
 .byte 65
 .byte 68
 .byte 10
 .text

# Entry to: prfloat
# ENTRY   K7 C112 C114 C102 C108 C111 C97 C116
# LAB     L4

LA4:
 movl %ebp,0(%edx)
 movl %edx,%ebp
 popl %edx
 movl %edx,4(%ebp)
 movl %eax,8(%ebp)
 movl %ebx,12(%ebp)
# LSTR    M9078
 leal MA9078,%ebx
 shrl $2,%ebx
# SP      P7
 movl %ebx,28(%ebp)
# LP      P3
 movl 12(%ebp),%ebx
# JLS0    L18
 orl %ebx,%ebx
 jl LA18
# L       K43
 movl $43,%ebx
# J       L17
 jmp LA17
# LAB     L18
LA18:
# L       K45
 movl $45,%ebx
# LAB     L17
LA17:
# SP      P8
 movl %ebx,32(%ebp)
# LP      P7
 movl 28(%ebp),%ebx
# KPG     P4 G94
 movl 376(%esi),%eax
 leal 16(%ebp),%edx
 call *%eax
# LP      P3
 movl 12(%ebp),%ebx
# ATBL    K23
 movl %ebx,%ecx
 movl $23,%ebx
# RSH
 xchgl %ebx,%ecx
 cmpl $32,%ecx
 sbbl %eax,%eax
 andl %eax,%ebx
 shrl %cl,%ebx
# ATBL    K255
 movl %ebx,%ecx
 movl $255,%ebx
# AND
 andl %ecx,%ebx
# SP      P8
 movl %ebx,32(%ebp)
# LSTR    M9079
 leal MA9079,%ebx
 shrl $2,%ebx
# KPG     P4 G94
 movl 376(%esi),%eax
 leal 16(%ebp),%edx
 call *%eax
# L       K8388607
 movl $8388607,%ebx
# ATBLP   P3
 movl %ebx,%ecx
 movl 12(%ebp),%ebx
# AND
 andl %ecx,%ebx
# SP      P8
 movl %ebx,32(%ebp)
# LSTR    M9080
 leal MA9080,%ebx
 shrl $2,%ebx
# KPG     P4 G94
 movl 376(%esi),%eax
 leal 16(%ebp),%edx
 call *%eax
# RTN
 movl 4(%ebp),%eax
 movl 0(%ebp),%ebp
 jmp *%eax
# STRING  M9078 K4 C32 C32 C37 C99
.data
 .align 4
MA9078:
 .byte 4
 .byte 32
 .byte 32
 .byte 37
 .byte 99
 .text
# STRING  M9079 K4 C32 C37 C56 C98
.data
 .align 4
MA9079:
 .byte 4
 .byte 32
 .byte 37
 .byte 56
 .byte 98
 .text
# STRING  M9080 K5 C32 C37 C50 C51 C98
.data
 .align 4
MA9080:
 .byte 5
 .byte 32
 .byte 37
 .byte 50
 .byte 51
 .byte 98
 .text
# GLOBAL K1

.globl prog

.globl _prog
prog:
_prog:
 movl 4(%esp),%eax
# G1 L1
 movl $LA1,4(%eax)
# G201
 ret

# MODEND
