# Code generated by sial-386

.text
.align 16
# MODSTART# top: none
     f_none 0

# SECTION K4 C112 C114 C111 C103# top: none
     f_none 0


# Entry to: start
# ENTRY   K5 C115 C116 C97 C114 C116
# LAB     L1

LA1:
 movl %ebp,0(%edx)
 movl %edx,%ebp
 popl %edx
 movl %edx,4(%ebp)
 movl %eax,8(%ebp)
 movl %ebx,12(%ebp)
# LLP     P4# top: none
     f_none 0

 leal 16(%ebp),%ebx
 shrl $2,%ebx
# SP      P3# top: none
     f_none 0

 movl %ebx,12(%ebp)
# LLP     P56# top: none
     f_none 0

 leal 224(%ebp),%ebx
 shrl $2,%ebx
# SP      P55# top: none
     f_none 0

 movl %ebx,220(%ebp)
# L       K0# top: none
     f_none 0

 xorl %ebx,%ebx
# SP      P107# top: none
     f_none 0

 movl %ebx,428(%ebp)
# LP      P3# top: none
     f_none 0

 movl 12(%ebp),%ebx
# SP      P112# top: none
     f_none 0

 movl %ebx,448(%ebp)
# L       K50# top: none
     f_none 0

 movl $50,%ebx
# SP      P113# top: none
     f_none 0

 movl %ebx,452(%ebp)
# LSTR    M9001# top: none
     f_none 0

 leal MA9001,%ebx
 shrl $2,%ebx
# KPG     P108 G102# top: none
     f_none 0

 movl 408(%esi),%eax
 leal 432(%ebp),%edx
 call *%eax
# JNE0    L3# top: none
     f_none 0

 orl %ebx,%ebx
 jne LA3
# LSTR    M9002# top: none
     f_none 0

 leal MA9002,%ebx
 shrl $2,%ebx
# KPG     P108 G89# top: none
     f_none 0

 movl 356(%esi),%eax
 leal 432(%ebp),%edx
 call *%eax
# L       K20# top: none
     f_none 0

 movl $20,%ebx
# RTN# top: none
     f_none 0

 movl 4(%ebp),%eax
 movl 0(%ebp),%ebp
 jmp *%eax
# LAB     L3# top: none
     f_none 0

LA3:
# LSTR    M9003# top: none
     f_none 0

 leal MA9003,%ebx
 shrl $2,%ebx
# KPG     P108 G89# top: none
     f_none 0

 movl 356(%esi),%eax
 leal 432(%ebp),%edx
 call *%eax
# LSTR    M9004# top: none
     f_none 0

 leal MA9004,%ebx
 shrl $2,%ebx
# SP      P111# top: none
     f_none 0

 movl %ebx,444(%ebp)
# LKP     K0 P3# top: none
     f_none 0

 movl 12(%ebp),%eax
 movl 0(,%eax,4),%ebx
# JEQ0    L5# top: none
     f_none 0

 orl %ebx,%ebx
 je LA5
# J       L4# top: none
     f_none 0

 jmp LA4
# LAB     L5# top: none
     f_none 0

LA5:
# LSTR    M9005# top: none
     f_none 0

 leal MA9005,%ebx
 shrl $2,%ebx
# LAB     L4# top: none
     f_none 0

LA4:
# SP      P112# top: none
     f_none 0

 movl %ebx,448(%ebp)
# LP      P111# top: none
     f_none 0

 movl 444(%ebp),%ebx
# KPG     P108 G94# top: none
     f_none 0

 movl 376(%esi),%eax
 leal 432(%ebp),%edx
 call *%eax
# LSTR    M9006# top: none
     f_none 0

 leal MA9006,%ebx
 shrl $2,%ebx
# SP      P111# top: none
     f_none 0

 movl %ebx,444(%ebp)
# LKP     K1 P3# top: none
     f_none 0

 movl 12(%ebp),%eax
 movl 4(,%eax,4),%ebx
# JEQ0    L7# top: none
     f_none 0

 orl %ebx,%ebx
 je LA7
# J       L6# top: none
     f_none 0

 jmp LA6
# LAB     L7# top: none
     f_none 0

LA7:
# LSTR    M9007# top: none
     f_none 0

 leal MA9007,%ebx
 shrl $2,%ebx
# LAB     L6# top: none
     f_none 0

LA6:
# SP      P112# top: none
     f_none 0

 movl %ebx,448(%ebp)
# LP      P111# top: none
     f_none 0

 movl 444(%ebp),%ebx
# KPG     P108 G94# top: none
     f_none 0

 movl 376(%esi),%eax
 leal 432(%ebp),%edx
 call *%eax
# LSTR    M9008# top: none
     f_none 0

 leal MA9008,%ebx
 shrl $2,%ebx
# SP      P111# top: none
     f_none 0

 movl %ebx,444(%ebp)
# LKP     K2 P3# top: none
     f_none 0

 movl 12(%ebp),%eax
 movl 8(,%eax,4),%ebx
# JEQ0    L9# top: none
     f_none 0

 orl %ebx,%ebx
 je LA9
# LSTR    M9009# top: none
     f_none 0

 leal MA9009,%ebx
 shrl $2,%ebx
# J       L8# top: none
     f_none 0

 jmp LA8
# LAB     L9# top: none
     f_none 0

LA9:
# LSTR    M9010# top: none
     f_none 0

 leal MA9010,%ebx
 shrl $2,%ebx
# LAB     L8# top: none
     f_none 0

LA8:
# SP      P112# top: none
     f_none 0

 movl %ebx,448(%ebp)
# LP      P111# top: none
     f_none 0

 movl 444(%ebp),%ebx
# KPG     P108 G94# top: none
     f_none 0

 movl 376(%esi),%eax
 leal 432(%ebp),%edx
 call *%eax
# LSTR    M9011# top: none
     f_none 0

 leal MA9011,%ebx
 shrl $2,%ebx
# KPG     P108 G89# top: none
     f_none 0

 movl 356(%esi),%eax
 leal 432(%ebp),%edx
 call *%eax
# LG      G13# top: none
     f_none 0

 movl 52(%esi),%ebx
# KPG     P108 G43# top: none
     f_none 0

 movl 172(%esi),%eax
 leal 432(%ebp),%edx
 call *%eax
# LAB     L10# top: none
     f_none 0

LA10:
# KPG     P108 G38# top: none
     f_none 0

 movl 152(%esi),%eax
 leal 432(%ebp),%edx
 call *%eax
# SP      P108# top: none
     f_none 0

 movl %ebx,432(%ebp)
# ATBL    K10# top: none
     f_none 0

 movl %ebx,%ecx
 movl $10,%ebx
# JEQ     L12# top: none
     f_none 0

 cmpl %ebx,%ecx
 je LA12
# LM      K1# top: none
     f_none 0

 movl $-1,%ebx
# JNE     L11# top: none
     f_none 0

 cmpl %ebx,%ecx
 jne LA11
# LAB     L12# top: none
     f_none 0

LA12:
# J       L13# top: none
     f_none 0

 jmp LA13
# LAB     L11# top: none
     f_none 0

LA11:
# IKP     K1 P107# top: none
     f_none 0

 movl 428(%ebp),%ebx
 incl %ebx
 movl %ebx,428(%ebp)
# LP      P108# top: none
     f_none 0

 movl 432(%ebp),%ebx
# ATC# top: none
     f_none 0

 movl %ebx,%edx
# LP      P55# top: none
     f_none 0

 movl 220(%ebp),%ebx
# ATBLP   P107# top: none
     f_none 0

 movl %ebx,%ecx
 movl 428(%ebp),%ebx
# PBYT# top: none
     f_none 0

 movb %dl,(%ebx,%ecx,4)
# J       L10# top: none
     f_none 0

 jmp LA10
# LAB     L13# top: none
     f_none 0

LA13:
# LP      P107# top: none
     f_none 0

 movl 428(%ebp),%ebx
# ATC# top: none
     f_none 0

 movl %ebx,%edx
# LP      P55# top: none
     f_none 0

 movl 220(%ebp),%ebx
# ATBL    K0# top: none
     f_none 0

 movl %ebx,%ecx
 movl $0,%ebx
# PBYT# top: none
     f_none 0

 movb %dl,(%ebx,%ecx,4)
# LP      P55# top: none
     f_none 0

 movl 220(%ebp),%ebx
# SP      P112# top: none
     f_none 0

 movl %ebx,448(%ebp)
# LSTR    M9012# top: none
     f_none 0

 leal MA9012,%ebx
 shrl $2,%ebx
# KPG     P108 G94# top: none
     f_none 0

 movl 376(%esi),%eax
 leal 432(%ebp),%edx
 call *%eax
# L       K0# top: none
     f_none 0

 xorl %ebx,%ebx
# RTN# top: none
     f_none 0

 movl 4(%ebp),%eax
 movl 0(%ebp),%ebp
 jmp *%eax
# STRING  M9001 K10 C120 C44 C121 C47 C75 C44 C115 C119 C47 C83
.data
 .align 4
MA9001:
 .byte 10
 .byte 120
 .byte 44
 .byte 121
 .byte 47
 .byte 75
 .byte 44
 .byte 115
 .byte 119
 .byte 47
 .byte 83
 .text
# STRING  M9002 K23 C66 C97 C100 C32 C97 C114 C103 C117 C109 C101 C110 C116 C115 C32 C102 C111 C114 C32 C80 C82 C79 C71 C10
.data
 .align 4
MA9002:
 .byte 23
 .byte 66
 .byte 97
 .byte 100
 .byte 32
 .byte 97
 .byte 114
 .byte 103
 .byte 117
 .byte 109
 .byte 101
 .byte 110
 .byte 116
 .byte 115
 .byte 32
 .byte 102
 .byte 111
 .byte 114
 .byte 32
 .byte 80
 .byte 82
 .byte 79
 .byte 71
 .byte 10
 .text
# STRING  M9003 K21 C84 C104 C101 C32 C97 C114 C103 C117 C109 C101 C110 C116 C115 C32 C119 C101 C114 C101 C58 C10 C10
.data
 .align 4
MA9003:
 .byte 21
 .byte 84
 .byte 104
 .byte 101
 .byte 32
 .byte 97
 .byte 114
 .byte 103
 .byte 117
 .byte 109
 .byte 101
 .byte 110
 .byte 116
 .byte 115
 .byte 32
 .byte 119
 .byte 101
 .byte 114
 .byte 101
 .byte 58
 .byte 10
 .byte 10
 .text
# STRING  M9004 K23 C97 C114 C103 C49 C58 C32 C107 C101 C121 C119 C111 C114 C100 C32 C120 C58 C32 C32 C32 C32 C37 C115 C10
.data
 .align 4
MA9004:
 .byte 23
 .byte 97
 .byte 114
 .byte 103
 .byte 49
 .byte 58
 .byte 32
 .byte 107
 .byte 101
 .byte 121
 .byte 119
 .byte 111
 .byte 114
 .byte 100
 .byte 32
 .byte 120
 .byte 58
 .byte 32
 .byte 32
 .byte 32
 .byte 32
 .byte 37
 .byte 115
 .byte 10
 .text
# STRING  M9005 K11 C60 C110 C111 C116 C32 C103 C105 C118 C101 C110 C62
.data
 .align 4
MA9005:
 .byte 11
 .byte 60
 .byte 110
 .byte 111
 .byte 116
 .byte 32
 .byte 103
 .byte 105
 .byte 118
 .byte 101
 .byte 110
 .byte 62
 .text
# STRING  M9006 K23 C97 C114 C103 C49 C58 C32 C107 C101 C121 C119 C111 C114 C100 C32 C121 C47 C75 C58 C32 C32 C37 C115 C10
.data
 .align 4
MA9006:
 .byte 23
 .byte 97
 .byte 114
 .byte 103
 .byte 49
 .byte 58
 .byte 32
 .byte 107
 .byte 101
 .byte 121
 .byte 119
 .byte 111
 .byte 114
 .byte 100
 .byte 32
 .byte 121
 .byte 47
 .byte 75
 .byte 58
 .byte 32
 .byte 32
 .byte 37
 .byte 115
 .byte 10
 .text
# STRING  M9007 K11 C60 C110 C111 C116 C32 C103 C105 C118 C101 C110 C62
.data
 .align 4
MA9007:
 .byte 11
 .byte 60
 .byte 110
 .byte 111
 .byte 116
 .byte 32
 .byte 103
 .byte 105
 .byte 118
 .byte 101
 .byte 110
 .byte 62
 .text
# STRING  M9008 K23 C97 C114 C103 C49 C58 C32 C107 C101 C121 C119 C111 C114 C100 C32 C115 C119 C47 C83 C58 C32 C37 C115 C10
.data
 .align 4
MA9008:
 .byte 23
 .byte 97
 .byte 114
 .byte 103
 .byte 49
 .byte 58
 .byte 32
 .byte 107
 .byte 101
 .byte 121
 .byte 119
 .byte 111
 .byte 114
 .byte 100
 .byte 32
 .byte 115
 .byte 119
 .byte 47
 .byte 83
 .byte 58
 .byte 32
 .byte 37
 .byte 115
 .byte 10
 .text
# STRING  M9009 K4 C84 C82 C85 C69
.data
 .align 4
MA9009:
 .byte 4
 .byte 84
 .byte 82
 .byte 85
 .byte 69
 .text
# STRING  M9010 K5 C70 C65 C76 C83 C69
.data
 .align 4
MA9010:
 .byte 5
 .byte 70
 .byte 65
 .byte 76
 .byte 83
 .byte 69
 .text
# STRING  M9011 K23 C10 C84 C121 C112 C101 C32 C97 C32 C108 C105 C110 C101 C32 C111 C102 C32 C105 C110 C112 C117 C116 C58 C32
.data
 .align 4
MA9011:
 .byte 23
 .byte 10
 .byte 84
 .byte 121
 .byte 112
 .byte 101
 .byte 32
 .byte 97
 .byte 32
 .byte 108
 .byte 105
 .byte 110
 .byte 101
 .byte 32
 .byte 111
 .byte 102
 .byte 32
 .byte 105
 .byte 110
 .byte 112
 .byte 117
 .byte 116
 .byte 58
 .byte 32
 .text
# STRING  M9012 K15 C89 C111 C117 C32 C116 C121 C112 C101 C100 C58 C32 C37 C115 C10 C10
.data
 .align 4
MA9012:
 .byte 15
 .byte 89
 .byte 111
 .byte 117
 .byte 32
 .byte 116
 .byte 121
 .byte 112
 .byte 101
 .byte 100
 .byte 58
 .byte 32
 .byte 37
 .byte 115
 .byte 10
 .byte 10
 .text
# GLOBAL K1

.globl prog

.globl _prog
prog:
_prog:
 movl 4(%esp),%eax
# G1 L1
 movl $LA1,4(%eax)
# G102
 ret

# MODEND# top: none
     f_none 0

